 - name: Install python-pip library  # prerequisite for ubuntu machines #
    apt: name='{{item}}'
    with_items:
     - python-pip
     - python-dev
  - name: Install python-boto library
    pip: name=boto
  - name: Create AWS Instances
    ec2:                         # Change the key, image, region as per your account #
     key_name: "AJ"
     instance_type: "t2.micro"
     image: "ami-0e2ff28bfb72a4e45"
     wait: true
     region: "us-east-1"
    register: ec2
  - debug: var=item
    with_items: ec2.instances
